Import teste datam

In [7]:
import pandas as pd

file = "/home/bruno/Documents/Python/100DaysChallenge/python/input/house_prices/train.csv"
raw_data = pd.read_csv(file) 
raw_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [8]:
raw_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [25]:
y = raw_data.SalePrice

In [26]:
y.describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

Selecionar caracterisitacas do apt.
Primeiro vou tentar com todas e ver a precisão.
Verifiquei aqui, que só pode ser utilizado valores numéricos, se quiser usar por exemplo se uma rua gera um determinado preço, não é com o modelo que aprendi até agora.

Um ideia para tratar os campos que não são numeros é tratalos como numero, requer um trabalho maior e posso fazer depois. Ex. se for sim ou não, colocar S = 1 e N = 0

In [34]:

caract = ['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition']

In [74]:
# Apenas dados dunmericos nas caracteristicas
caract = ['MSSubClass','LotFrontage', 'LotArea','YearBuilt', 'YearRemodAdd','BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GarageArea', 
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea','MiscVal', 'MoSold', 'YrSold']

In [77]:
X = raw_data[caract]
X.describe()

,MSSubClass,LotFrontage,LotArea,YearBuilt,YearRemodAdd,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,1971.267808,1984.865753,46.549315,567.240411,1057.429452,1162.626712,346.992466,472.980137,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753
std,42.300571,24.284752,9981.264932,30.202904,20.645407,161.319273,441.866955,438.705324,386.587738,436.528436,213.804841,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095
min,20.000000,21.000000,1300.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,20.000000,59.000000,7553.500000,1954.000000,1967.000000,0.000000,223.000000,795.750000,882.000000,0.000000,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000
50%,50.000000,69.000000,9478.500000,1973.000000,1994.000000,0.000000,477.500000,991.500000,1087.000000,0.000000,480.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,70.000000,80.000000,11601.500000,2000.000000,2004.000000,0.000000,808.000000,1298.250000,1391.250000,728.000000,576.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,190.000000,313.000000,215245.000000,2010.000000,2010.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,1418.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000

In [78]:
X.head(100)

,MSSubClass,LotFrontage,LotArea,YearBuilt,YearRemodAdd,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,60,65.0,8450,2003,2003,0,150,856,856,854,548,0,0,0,0,0,2,2008
1,20,80.0,9600,1976,1976,0,284,1262,1262,0,460,0,0,0,0,0,5,2007
2,60,68.0,11250,2001,2002,0,434,920,920,866,608,0,0,0,0,0,9,2008
3,70,60.0,9550,1915,1970,0,540,756,961,756,642,272,0,0,0,0,2,2006
4,60,84.0,14260,2000,2000,0,490,1145,1145,1053,836,0,0,0,0,0,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,60,NaN,9765,1993,1993,0,370,680,680,790,420,0,0,0,0,480,4,2009
96,20,78.0,10264,1999,1999,0,426,1588,1588,0,472,0,0,0,0,0,8,2006
97,20,73.0,10921,1965,1965,0,440,960,960,0,432,0,0,0,0,0,5,2007
98,30,85.0,10625,1920,1950,0,350,458,835,0,366,77,0,0,0,400,5,2010
99,20,77.0,9320,1959,1959,0,381,950,1225,0,0,0,0,0,0,400,1,2010

Testando modelos

1 - Decision Tree

In [94]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_absolute_error

# Aliminando os NaN
X2 = np.nan_to_num(X)

#Dividindo dados
train_X, val_X, train_y, val_y = train_test_split(X2, y, random_state = 0)

# Define model. Specify a number for random_state to ensure same results each run
model1 = DecisionTreeRegressor(random_state=1)

# Fit model
model1.fit(train_X,train_y)

val_predictions = model1.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

for max_leaf_nodes in [5, 50, 500, 5000, 50000,500000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

29733.44383561644
Max leaf nodes: 5  		 Mean Absolute Error:  35757
Max leaf nodes: 50  		 Mean Absolute Error:  29655
Max leaf nodes: 500  		 Mean Absolute Error:  31047
Max leaf nodes: 5000  		 Mean Absolute Error:  31150
Max leaf nodes: 50000  		 Mean Absolute Error:  31150
Max leaf nodes: 500000  		 Mean Absolute Error:  31150

In [119]:
from sklearn.ensemble import RandomForestRegressor

forest_model = RandomForestRegressor(random_state=5)
forest_model.fit(train_X, train_y)
preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, preds))

20861.17567123288

In [120]:
print(preds[1])

143954.84

In [121]:
print(val_y[1])

181500

## Usando os dados de teste

In [122]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

file = "/home/bruno/Documents/Python/100DaysChallenge/python/input/house_prices/test.csv"
raw_data = pd.read_csv(file) 

caract = ['MSSubClass','LotFrontage', 'LotArea','YearBuilt', 'YearRemodAdd','BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GarageArea', 
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea','MiscVal', 'MoSold', 'YrSold']

XT = raw_data[caract]

forest_model = RandomForestRegressor(random_state=5)
preds = forest_model.predict(XT)

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.